#!/usr/bin/env php
<?php
# https://www.doctrine-project.org/projects/doctrine-migrations/en/1.7/reference/introduction.html#introduction
namespace WIPCMS\core\console;

use Symfony\Component\Console\Application;

require __DIR__ . '/../../vendor/autoload.php';
require __DIR__ . '/../../config/config.php';

$application = new Application();
$application->setHelperSet(include __DIR__ . '/../../config/cli-config.php');

$application->addCommands([
    new \Doctrine\DBAL\Migrations\Tools\Console\Command\ExecuteCommand(),
    new \Doctrine\DBAL\Migrations\Tools\Console\Command\GenerateCommand(),
    new \Doctrine\DBAL\Migrations\Tools\Console\Command\LatestCommand(),
    new \Doctrine\DBAL\Migrations\Tools\Console\Command\MigrateCommand(),
    new \Doctrine\DBAL\Migrations\Tools\Console\Command\StatusCommand(),
    new \Doctrine\DBAL\Migrations\Tools\Console\Command\VersionCommand(),
    new \Doctrine\DBAL\Migrations\Tools\Console\Command\DiffCommand(),
    new \Doctrine\DBAL\Migrations\Tools\Console\Command\UpToDateCommand()
]);

$application->run();